inherit_gem:
  rubocop-github:
    - config/default_edge.yml
    - config/rails_edge.yml

# Just for the sake of having all the cops enabled. Production-wise, this is not recommended
AllCops:
  NewCops: disable
  TargetRubyVersion: "2.5"

Layout/ArgumentAlignment:
  Enabled: false

Style/Documentation:
  Enabled: false