inherit_gem:
  rubocop-github:
    - config/default_edge.yml
    - config/rails_edge.yml

AllCops:
  Exclude:
    - 'inventory.rb'
  NewCops: disable
  TargetRubyVersion: "2.5"

Layout/ArgumentAlignment:
  Enabled: false

Style/Documentation:
  Enabled: false